### ISSUE TITLE
 cant  open the "example" project.  :(

### ISSUE THREAD

**Issue by BoneSun** [UltraCoderRU/screepsxx#1]
reference to "readme" goes well ,very smoothly.

but ! cant  open the "example" project.  :(

not founds!

#include <Screeps/Context.hpp>
#include <Screeps/Creep.hpp>
#include <emscripten.h>
#include <emscripten/bind.h>

use clion !

**Comment by kirirururu** [comment]
Hi! Sorry for the wait, I've been very busy the last few days.

There was some inconsistency in README and example project. The last one was intended to be build inside screepsxx directory, that is not, what you usually want. So I updated them. Please, let me know, if this helps you.
