### ISSUE TITLE
Got error "Cannot read properties of undefined (reading 'creeps')" in example

### ISSUE THREAD

**Issue by guquan-lengyue** [UltraCoderRU/screepsxx#2]
## env
+ cmake version 3.23.2
+ emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.12 (38d1292ba2f5b4a7c8518931f5ae6f97ef0f6827)
+ ninjia version 1.10
+ screeps word website playground

## step
```bash
mkdir -p build
cd build
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake ..
cmake --build .
```
## result
![image](https://user-images.githubusercontent.com/56825011/171025324-a140f200-46e8-4a97-ad89-299ff0f4b145.png)
![image](https://user-images.githubusercontent.com/56825011/171025380-73f3a895-e808-4e44-8fc2-5bb22c2cdb07.png)

**Comment by kirirururu** [comment]
Hello. Sorry, but I can not reproduce this error.
