### ISSUE TITLE
simModeErr

### ISSUE THREAD

**Issue by Qsirman** [UltraCoderRU/screepsxx#3]
Thanks for your sharing and code runs well on public server. 

However, it crashed when I run it in simulation mode as below. Maybe you can fix it?

`Cannot read properties of undefined (reading 'location')`

BTW: I only tested the example code and did not modify myself.

**Comment by kirirururu** [comment]
I do remember that in the beginning of development I also had problems with running WASM in simulation environment. I believe, latter just doesn't support WASM. I chose not to mess around and switched to public server. :)

**Comment by UltraCoderRU** [comment]
Closing as not planned.
